### ISSUE TITLE
Can't build current master

### ISSUE THREAD

**Issue by hcwiley** [rafmudaf/Laplace#1]
You haven't included `image_kernels.cpp` and `image_kernels.hpp` so I get build errors.
<img width="1325" alt="Screenshot 2019-05-22 10 44 37" src="https://user-images.githubusercontent.com/1400808/58188763-d3a46280-7c7e-11e9-91ef-d6210749065a.png">

**Comment by rafmudaf** [comment]
@hcwiley thanks for pointing this out. I've fixed the project in both the `master` and `develop` branch. Let me know if any build problems persist.
